/obj/machinery/mineral/equipment_vendor/fastfood/costumes
	desc = "Purchase a mask for that ugly mug."
	prize_list = list(new /datum/data/mining_equipment("balaclava",	 /obj/item/clothing/mask/vampire/balaclava,	10),
		new /datum/data/mining_equipment("bear mask",	 /obj/item/clothing/mask/animal/rat/bear,	13),
		new /datum/data/mining_equipment("rat mask",	/obj/item/clothing/mask/animal/rat,	10),
		new /datum/data/mining_equipment("bee mask",	/obj/item/clothing/mask/animal/rat/bee,	12),
		new /datum/data/mining_equipment("fox mask",	/obj/item/clothing/mask/animal/rat/fox,	10),
		new /datum/data/mining_equipment("bat mask",	/obj/item/clothing/mask/animal/rat/bat,	15),
		new /datum/data/mining_equipment("raven mask",	/obj/item/clothing/mask/animal/rat/raven,	20),
		new /datum/data/mining_equipment("jackal mask",	 /obj/item/clothing/mask/animal/rat/jackal,	20),
		new /datum/data/mining_equipment("medical mask",	/obj/item/clothing/mask/surgical,	10),
		new /datum/data/mining_equipment("mummy mask",	/obj/item/clothing/mask/mummy,	15),
		new /datum/data/mining_equipment("scarecrow mask",	/obj/item/clothing/mask/scarecrow,	10),
		new /datum/data/mining_equipment("respirator",	/obj/item/clothing/mask/vampire,	35),
		new /datum/data/mining_equipment("black and gold luchador mask",	/obj/item/clothing/mask/luchador/tecnicos,	10),
		new /datum/data/mining_equipment("green luchador mask",	/obj/item/clothing/mask/luchador,	10),
		new /datum/data/mining_equipment("red and blue luchador mask",	/obj/item/clothing/mask/luchador/rudos,	10),
		new /datum/data/mining_equipment("Venetian mask",	/obj/item/clothing/mask/vampire/venetian_mask,	30),
		new /datum/data/mining_equipment("fancy Venetian mask",	/obj/item/clothing/mask/vampire/venetian_mask/fancy,	200),
		new /datum/data/mining_equipment("jester mask",	/obj/item/clothing/mask/vampire/venetian_mask/jester,	50),
		new /datum/data/mining_equipment("bloody mask",	/obj/item/clothing/mask/vampire/venetian_mask/scary,	30),
		new /datum/data/mining_equipment("comedy mask", /obj/item/clothing/mask/vampire/comedy,	25),
		new /datum/data/mining_equipment("tragedy mask", /obj/item/clothing/mask/vampire/tragedy,	25),
		new /datum/data/mining_equipment("shemagh",	 /obj/item/clothing/mask/vampire/shemagh,	20),
		new /datum/data/mining_equipment("fake italian moustache", /obj/item/clothing/mask/fakemoustache/italian, 20),
		new /datum/data/mining_equipment("dracula costume",	 /obj/item/clothing/suit/dracula, 300),
		// TFN EDIT ADDITION START: re-add robes and hats
		new /datum/data/mining_equipment("student robe",	 /obj/item/clothing/suit/chaplainsuit/studentuni, 100),
		new /datum/data/mining_equipment("white robes",	/obj/item/clothing/suit/hooded/robes,	40),
		new /datum/data/mining_equipment("black robes",	/obj/item/clothing/suit/hooded/robes/black,	40),
		new /datum/data/mining_equipment("grey robes",	/obj/item/clothing/suit/hooded/robes/grey,	40),
		new /datum/data/mining_equipment("dark red robes",	/obj/item/clothing/suit/hooded/robes/darkred,	40),
		new /datum/data/mining_equipment("yellow robes",	/obj/item/clothing/suit/hooded/robes/yellow,	40),
		new /datum/data/mining_equipment("green robes",	/obj/item/clothing/suit/hooded/robes/green,	40),
		new /datum/data/mining_equipment("red robes",	/obj/item/clothing/suit/hooded/robes/red,	40),
		new /datum/data/mining_equipment("blue robes", /obj/item/clothing/suit/hooded/robes/blue,	40),
		new /datum/data/mining_equipment("purple robes",	/obj/item/clothing/suit/hooded/robes/purple,	40),
		new /datum/data/mining_equipment("blue wizard hat",	/obj/item/clothing/head/vampire/wizard/blue, 25),
		new /datum/data/mining_equipment("red wizard hat",	/obj/item/clothing/head/vampire/wizard/red, 25),
		new /datum/data/mining_equipment("yellow wizard hat",	/obj/item/clothing/head/vampire/wizard/yellow, 25),
		new /datum/data/mining_equipment("green wizard hat",	/obj/item/clothing/head/vampire/wizard/green, 25),
		new /datum/data/mining_equipment("dark red wizard hat",	/obj/item/clothing/head/vampire/wizard/darkred, 25),
		new /datum/data/mining_equipment("grey wizard hat",	/obj/item/clothing/head/vampire/wizard/grey, 25),
		new /datum/data/mining_equipment("white wizard hat",	/obj/item/clothing/head/vampire/wizard/white, 25),
		new /datum/data/mining_equipment("black wizard hat",	/obj/item/clothing/head/vampire/wizard/black, 25),
		new /datum/data/mining_equipment("purple wizard hat",	/obj/item/clothing/head/vampire/wizard/purple, 25),
		// TFN EDIT ADDITION END
		// REQUIEM WARDROBE ADDITION
		new /datum/data/mining_equipment("white veil",		/obj/item/clothing/glasses/vampire/vtr/white_veil, 25 ),
		new /datum/data/mining_equipment("black veil", /obj/item/clothing/glasses/vampire/vtr/black_veil, 25 ),
		new /datum/data/mining_equipment("brown cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboyhat, 20),
		new /datum/data/mining_equipment("black cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboy_black, 20),
		new /datum/data/mining_equipment("wide cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboy_wide, 20),
		new /datum/data/mining_equipment("white cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboy_white, 20),
		new /datum/data/mining_equipment("white wide cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboy_white_wide, 20),
		new /datum/data/mining_equipment("fuzzy monster hat", /obj/item/clothing/head/vampire/vtr/fuzzy, 20),
		new /datum/data/mining_equipment("fez", /obj/item/clothing/head/vampire/vtr/fez, 20),
		new /datum/data/mining_equipment("feathered hat", /obj/item/clothing/head/vampire/vtr/feather_trilby, 20),
		new /datum/data/mining_equipment("fedora", /obj/item/clothing/head/vampire/vtr/fedora, 20),
		new /datum/data/mining_equipment("mariner's cap", /obj/item/clothing/head/vampire/vtr/mariner, 20),
		new /datum/data/mining_equipment("white peaked cap", /obj/item/clothing/head/vampire/vtr/whitepeakcap, 20),
		new /datum/data/mining_equipment("biker cap", /obj/item/clothing/head/vampire/vtr/biker, 20),
		new /datum/data/mining_equipment("captain's hat", /obj/item/clothing/head/vampire/vtr/captain, 20),
		new /datum/data/mining_equipment("small cowboy hat", /obj/item/clothing/head/vampire/vtr/cowboy_small, 20),
		new /datum/data/mining_equipment("aviator cap", /obj/item/clothing/head/vampire/vtr/tank, 20),
		new /datum/data/mining_equipment("bucket hat", /obj/item/clothing/head/vampire/vtr/buckethat, 20),
		new /datum/data/mining_equipment("beaver hat", /obj/item/clothing/head/vampire/vtr/beaver_hat, 20),
		new /datum/data/mining_equipment("frilly headband", /obj/item/clothing/head/vampire/vtr/frillyheadband, 20),
		new /datum/data/mining_equipment("black headdress", /obj/item/clothing/head/vampire/vtr/black_headdress, 20),
		new /datum/data/mining_equipment("right eyepatch", /obj/item/clothing/glasses/vampire/vtr/eyepatch, 15),
		new /datum/data/mining_equipment("left eyepatch", /obj/item/clothing/glasses/vampire/vtr/eyepatch_alt, 15),
		new /datum/data/mining_equipment("medical eyepatch right", /obj/item/clothing/glasses/vampire/vtr/eyepatch_white, 15),
		new /datum/data/mining_equipment("medical eyepatch left", /obj/item/clothing/glasses/vampire/vtr/eyepatch_white_alt, 15),
		new /datum/data/mining_equipment("two-tone glasses", /obj/item/clothing/glasses/vampire/vtr/threedee, 15),
		new /datum/data/mining_equipment("panama hat", /obj/item/clothing/head/vampire/vtr/panama, 15),
		new /datum/data/mining_equipment("horrible tie", /obj/item/clothing/neck/vtr/tie/horrible, 10),
		new /datum/data/mining_equipment("authentic maid dress", /obj/item/clothing/under/vampire/vtr/maid, 40),)


/obj/machinery/mineral/equipment_vendor/fastfood/clothing
	desc = "Purchase all the finest outfits... Or don't, wagie.."
	prize_list = list(new /datum/data/mining_equipment("crimson red dress",	/obj/item/clothing/under/vampire/primogen_toreador/female,	350),
		new /datum/data/mining_equipment("black dress",	/obj/item/clothing/under/vampire/business,	250),
		new /datum/data/mining_equipment("leather pants", /obj/item/clothing/under/vampire/leatherpants,	200),
		new /datum/data/mining_equipment("camo pants", /obj/item/clothing/under/pants/camo, 100),
		new /datum/data/mining_equipment("jeans", /obj/item/clothing/under/pants/jeans, 100),
		new /datum/data/mining_equipment("track pants", /obj/item/clothing/under/pants/track, 100),
		new /datum/data/mining_equipment("slacks", /obj/item/clothing/under/pants/slacks, 100),
		new /datum/data/mining_equipment("fancy gray suit",	/obj/item/clothing/under/vampire/fancy_gray,	150),
		new /datum/data/mining_equipment("fancy red suit",	/obj/item/clothing/under/vampire/fancy_red,	150),
		new /datum/data/mining_equipment("black luxury suit",	/obj/item/clothing/under/vampire/ventrue,	50),
		new /datum/data/mining_equipment("black luxury suit skirt",	/obj/item/clothing/under/vampire/ventrue/female,	50),
		new /datum/data/mining_equipment("fancy black suit", /obj/item/clothing/under/vampire/prince,	500),
		new /datum/data/mining_equipment("fancy black suitskirt", /obj/item/clothing/under/vampire/prince/female,	500),
		new /datum/data/mining_equipment("white business suit",	/obj/item/clothing/under/vampire/office,	50),
		new /datum/data/mining_equipment("black overcoat",	/obj/item/clothing/under/vampire/rich,	45),
		new /datum/data/mining_equipment("burgundy suit",	/obj/item/clothing/under/vampire/tremere,	35),
		new /datum/data/mining_equipment("burgundy suit skirt",	/obj/item/clothing/under/vampire/tremere/female,	35),
		new /datum/data/mining_equipment("plain black suit",	 /obj/item/clothing/under/vampire/suit,	50),
		new /datum/data/mining_equipment("plain black suitskirt",	 /obj/item/clothing/under/vampire/suit/female,	50),
		new /datum/data/mining_equipment("plain red suit",	 /obj/item/clothing/under/vampire/sheriff,	80),
		new /datum/data/mining_equipment("plain red suitskirt",	 /obj/item/clothing/under/vampire/sheriff/female,	80),
		new /datum/data/mining_equipment("plain blue suit",	 /obj/item/clothing/under/vampire/clerk,	90),
		new /datum/data/mining_equipment("plain blue suitskirt",	 /obj/item/clothing/under/vampire/clerk/female,	90),
		new /datum/data/mining_equipment("brown suit",	 /obj/item/clothing/under/vampire/archivist,	60),
		new /datum/data/mining_equipment("brown suitskirt",	 /obj/item/clothing/under/vampire/archivist/female,	60),
		new /datum/data/mining_equipment("white suit",	 /obj/item/clothing/under/suit/white,	100),
		new /datum/data/mining_equipment("beige suit",	 /obj/item/clothing/under/suit/beige,	100),
		new /datum/data/mining_equipment("tuxedo",	 /obj/item/clothing/under/suit/tuxedo,	100),
		new /datum/data/mining_equipment("tan suit",	 /obj/item/clothing/under/suit/tan,	100),
		new /datum/data/mining_equipment("checkered suit",	 /obj/item/clothing/under/suit/checkered,	100),
		new /datum/data/mining_equipment("burgundy suit",	 /obj/item/clothing/under/suit/burgundy,	100),
		new /datum/data/mining_equipment("navy suit",	 /obj/item/clothing/under/suit/navy,	100),
		new /datum/data/mining_equipment("charcoal suit",	 /obj/item/clothing/under/suit/charcoal,	100),
		new /datum/data/mining_equipment("red suit",	 /obj/item/clothing/under/suit/red,	100),
		new /datum/data/mining_equipment("green suit",	 /obj/item/clothing/under/suit/green,	100),
		new /datum/data/mining_equipment("waiter suit",	 /obj/item/clothing/under/suit/waiter, 100),
		new /datum/data/mining_equipment("two piece suit",	 /obj/item/clothing/under/suit/blacktwopiece, 100),
		new /datum/data/mining_equipment("executive suit",	 /obj/item/clothing/under/suit/black_really, 100),
		new /datum/data/mining_equipment("executive suitskirt",	 /obj/item/clothing/under/suit/black_really/skirt, 100),
		new /datum/data/mining_equipment("dutch suit",	 /obj/item/clothing/under/costume/dutch, 100),
		new /datum/data/mining_equipment("dutch overcoat",	 /obj/item/clothing/suit/dutch, 100),
		new /datum/data/mining_equipment("hawaiian shirt",	 /obj/item/clothing/suit/hawaiian, 20),
		new /datum/data/mining_equipment("popular outfit",		/obj/item/clothing/under/vampire/scenepink,		20),
		new /datum/data/mining_equipment("moody attire",		/obj/item/clothing/under/vampire/scenemoody,		20),
		new /datum/data/mining_equipment("pim attire",		/obj/item/clothing/under/vampire/scenezim,		20),
		new /datum/data/mining_equipment("gamer shirt",	 /obj/item/clothing/suit/nerdshirt, 20),
		new /datum/data/mining_equipment("revealing outfit",		/obj/item/clothing/under/vampire/sceneleopard,		20),
		new /datum/data/mining_equipment("flamboyant outfit",	/obj/item/clothing/under/vampire/toreador,	30),
		new /datum/data/mining_equipment("female flamboyant outfit",	/obj/item/clothing/under/vampire/toreador/female,	30),
		new /datum/data/mining_equipment("purple and black outfit",	/obj/item/clothing/under/vampire/sexy,	25),
		new /datum/data/mining_equipment("slick jacket",	/obj/item/clothing/under/vampire/slickback,		25),
		new /datum/data/mining_equipment("tracksuit",	/obj/item/clothing/under/vampire/sport,	25),
		new /datum/data/mining_equipment("grimey pants",	/obj/item/clothing/under/vampire/malkavian,	20),
		new /datum/data/mining_equipment("odd goth schoolgirl attire",	/obj/item/clothing/under/vampire/malkavian/female,	20),
		new /datum/data/mining_equipment("gothic clothes",	/obj/item/clothing/under/vampire/gothic,	20),
		new /datum/data/mining_equipment("punk attire",	/obj/item/clothing/under/vampire/brujah,	20),
		new /datum/data/mining_equipment("female punk attire ",	/obj/item/clothing/under/vampire/brujah/female,	20),
		new /datum/data/mining_equipment("pentagram shirt",	/obj/item/clothing/under/vampire/baali,	20),
		new /datum/data/mining_equipment("pentagram skirt",	/obj/item/clothing/under/vampire/baali/female,	20),
		new /datum/data/mining_equipment("emo outfit",	/obj/item/clothing/under/vampire/emo,	20),
		new /datum/data/mining_equipment("red hipster outfit",	/obj/item/clothing/under/vampire/red,	20),
		new /datum/data/mining_equipment("messy shirt",	/obj/item/clothing/under/vampire/bouncer,	15),
		new /datum/data/mining_equipment("agent shirt",	/obj/item/clothing/under/vampire/hound,	15),
		new /datum/data/mining_equipment("cheap shirt",	/obj/item/clothing/under/vampire/homeless,	10),
		new /datum/data/mining_equipment("cheaper shirt",	/obj/item/clothing/under/vampire/homeless/female,	5),
		new /datum/data/mining_equipment("hazard vest",	 /obj/item/clothing/suit/hazardvest, 20),
		new /datum/data/mining_equipment("blue overalls",	/obj/item/clothing/under/vampire/mechanic,	20),
		new /datum/data/mining_equipment("black overalls",	 /obj/item/clothing/under/vampire/graveyard, 20),
		new /datum/data/mining_equipment("black grunge outfit",	/obj/item/clothing/under/vampire/black,	20),
		new /datum/data/mining_equipment("gimp outfit",	/obj/item/clothing/under/vampire/nosferatu,	15),
		new /datum/data/mining_equipment("female gimp outfit",	/obj/item/clothing/under/vampire/nosferatu/female,	15),
		new /datum/data/mining_equipment("rugged attire",	/obj/item/clothing/under/vampire/gangrel,	15),
		new /datum/data/mining_equipment("female rugged attire",	/obj/item/clothing/under/vampire/gangrel/female,	15),
		new /datum/data/mining_equipment("yellow sleeveless shirt",	/obj/item/clothing/under/vampire/larry,	15),
		new /datum/data/mining_equipment("white sleeveless shirt",	/obj/item/clothing/under/vampire/bandit,	15),
		new /datum/data/mining_equipment("white turtleneck", /obj/item/clothing/under/vampire/turtleneck_white,	15),
		new /datum/data/mining_equipment("black turtleneck", /obj/item/clothing/under/vampire/turtleneck_black,	15),
		new /datum/data/mining_equipment("red turtleneck",	/obj/item/clothing/under/vampire/turtleneck_red,	15),
		new /datum/data/mining_equipment("navy turtleneck",	/obj/item/clothing/under/vampire/turtleneck_navy,	15),
		new /datum/data/mining_equipment("tacticool turtleneck",	/obj/item/clothing/under/syndicate/tacticool, 15),
		new /datum/data/mining_equipment("biker outfit",	/obj/item/clothing/under/vampire/biker,	15),
		new /datum/data/mining_equipment("burlesque outfit", /obj/item/clothing/under/vampire/burlesque,	15),
		new /datum/data/mining_equipment("daisy dukes", /obj/item/clothing/under/vampire/burlesque/daisyd,	10),
		new /datum/data/mining_equipment("black shoes",	/obj/item/clothing/shoes/vampire,	10),
		new /datum/data/mining_equipment("brown shoes",	/obj/item/clothing/shoes/vampire/brown,	10),
		new /datum/data/mining_equipment("white shoes",	/obj/item/clothing/shoes/vampire/white,	10),
		new /datum/data/mining_equipment("black boots",	/obj/item/clothing/shoes/vampire/jackboots,	10),
		new /datum/data/mining_equipment("work boots",	/obj/item/clothing/shoes/vampire/jackboots/work,	10),
		new /datum/data/mining_equipment("white sneakers",	/obj/item/clothing/shoes/vampire/sneakers,	10),
		new /datum/data/mining_equipment("red sneakers",	/obj/item/clothing/shoes/vampire/sneakers/red,	10),
		new /datum/data/mining_equipment("high heels",	/obj/item/clothing/shoes/vampire/heels,	35),
		new /datum/data/mining_equipment("red high heels",	/obj/item/clothing/shoes/vampire/heels/red,	35),
		new /datum/data/mining_equipment("white high heels",	/obj/item/clothing/shoes/vampire/heels/white, 35),
		new /datum/data/mining_equipment("scaly shoes",	/obj/item/clothing/shoes/vampire/businessscaly,	35),
		new /datum/data/mining_equipment("black shoes",	/obj/item/clothing/shoes/vampire/businessblack,	35),
		new /datum/data/mining_equipment("black fur boots",	/obj/item/clothing/shoes/vampire/blackfur,	35),
		new /datum/data/mining_equipment("brown fur boots",	/obj/item/clothing/shoes/vampire/brownfur,	35),
		new /datum/data/mining_equipment("knee-high sneakers",	/obj/item/clothing/shoes/vampire/pumped,	35),
		new /datum/data/mining_equipment("metal tip shoes",	/obj/item/clothing/shoes/vampire/businesstip,	50),
		new /datum/data/mining_equipment("purple fur coat",		/obj/item/clothing/suit/vampire/slickbackcoat,	500),
		new /datum/data/mining_equipment("too much fancy jacket",	/obj/item/clothing/suit/vampire/majima_jacket,	100),
		new /datum/data/mining_equipment("labcoat",	/obj/item/clothing/suit/vampire/labcoat,	75),
		new /datum/data/mining_equipment("fancy gray jacket",	/obj/item/clothing/suit/vampire/fancy_gray,	50),
		new /datum/data/mining_equipment("fancy red jacket",	/obj/item/clothing/suit/vampire/fancy_red,	50),
		new /datum/data/mining_equipment("black trenchcoat",	/obj/item/clothing/suit/vampire/trench,	45),
		new /datum/data/mining_equipment("brown trenchcoat",	/obj/item/clothing/suit/vampire/trench/alt,	35),
		new /datum/data/mining_equipment("leopard coat",	/obj/item/clothing/suit/vampire/coat/leopard,	35),
		new /datum/data/mining_equipment("hoodie",	/obj/item/clothing/suit/hooded/hoodie,	35),
		new /datum/data/mining_equipment("intruder pim hoodie",	/obj/item/clothing/suit/hooded/hoodie/hoodie_pim,	35),
		new /datum/data/mining_equipment("brown coat",	/obj/item/clothing/suit/vampire/coat,	15),
		new /datum/data/mining_equipment("green coat",	/obj/item/clothing/suit/vampire/coat/alt,	15),
		new /datum/data/mining_equipment("black leather jacket",	/obj/item/clothing/suit/vampire/jacket,	15),
		new /datum/data/mining_equipment("black coat",	/obj/item/clothing/suit/vampire/coat/winter,	15),
		new /datum/data/mining_equipment("red coat",	/obj/item/clothing/suit/vampire/coat/winter/alt,	15),
		new /datum/data/mining_equipment("bomber jacket",	 /obj/item/clothing/suit/jacket, 60),
		new /datum/data/mining_equipment("puffer jacket",	 /obj/item/clothing/suit/jacket/puffer, 100),
		new /datum/data/mining_equipment("puffer vest",	 /obj/item/clothing/suit/jacket/puffer/vest, 100),
		new /datum/data/mining_equipment("military jacket",	 /obj/item/clothing/suit/jacket/miljacket, 60),
		new /datum/data/mining_equipment("letterman jacket",	 /obj/item/clothing/suit/jacket/letterman, 100),
		new /datum/data/mining_equipment("red letterman jacket",	 /obj/item/clothing/suit/jacket/letterman_red, 100),
		new /datum/data/mining_equipment("gothic coat",	 /obj/item/clothing/suit/gothcoat, 200),
		new /datum/data/mining_equipment("yellow aviators",	/obj/item/clothing/glasses/vampire/yellow,	20),
		new /datum/data/mining_equipment("red aviators",	/obj/item/clothing/glasses/vampire/red,	20),
		new /datum/data/mining_equipment("sunglasses",	/obj/item/clothing/glasses/vampire/sun,	20),
		new /datum/data/mining_equipment("prescription glasses",	/obj/item/clothing/glasses/vampire/perception,	20),
		new /datum/data/mining_equipment("eyepatch", /obj/item/clothing/glasses/eyepatch, 50),
		new /datum/data/mining_equipment("welding goggles", /obj/item/clothing/glasses/welding, 50),
		new /datum/data/mining_equipment("monocle", /obj/item/clothing/glasses/monocle, 50),
		new /datum/data/mining_equipment("leather gloves", /obj/item/clothing/gloves/vampire/leather,	25),
		new /datum/data/mining_equipment("rubber gloves", /obj/item/clothing/gloves/vampire/cleaning,	15),
		new /datum/data/mining_equipment("latex gloves", /obj/item/clothing/gloves/vampire/latex,	5),
		new /datum/data/mining_equipment("black work gloves", /obj/item/clothing/gloves/vampire/work,	45),
		new /datum/data/mining_equipment("bandana",	/obj/item/clothing/head/vampire/bandana,	10),
		new /datum/data/mining_equipment("red bandana",	/obj/item/clothing/head/vampire/bandana/red,	10),
		new /datum/data/mining_equipment("black bandana",	/obj/item/clothing/head/vampire/bandana/black,	10),
		new /datum/data/mining_equipment("baseball cap", /obj/item/clothing/head/vampire/baseballcap, 10),
		new /datum/data/mining_equipment("ushanka",	/obj/item/clothing/head/vampire/ushanka, 20),
		new /datum/data/mining_equipment("beanie",	/obj/item/clothing/head/vampire/beanie,	10),
		new /datum/data/mining_equipment("black beanie",	/obj/item/clothing/head/vampire/beanie/black,	10),
		new /datum/data/mining_equipment("rough beanie",	/obj/item/clothing/head/vampire/beanie/homeless,	10),
		new /datum/data/mining_equipment("red beret",	/obj/item/clothing/head/beret,	10),
		new /datum/data/mining_equipment("black beret",	/obj/item/clothing/head/beret/black,	10),
		new /datum/data/mining_equipment("flat cap", /obj/item/clothing/head/flatcap, 80),
		new /datum/data/mining_equipment("cowboy hat", /obj/item/clothing/head/vampire/cowboy, 80),
		new /datum/data/mining_equipment("fedora", /obj/item/clothing/head/fedora, 80),
		new /datum/data/mining_equipment("beige fedora", /obj/item/clothing/head/fedora/beige, 80),
		new /datum/data/mining_equipment("white fedora", /obj/item/clothing/head/fedora/white, 80),
		new /datum/data/mining_equipment("top hat", /obj/item/clothing/head/vampire/top, 80),
		new /datum/data/mining_equipment("chauffeur hat", /obj/item/clothing/head/vampire/chauffeur, 80),
		new /datum/data/mining_equipment("blue tie",	/obj/item/clothing/neck/tie/blue,	10),
		new /datum/data/mining_equipment("red tie",	/obj/item/clothing/neck/tie/red,	10),
		new /datum/data/mining_equipment("black tie",	/obj/item/clothing/neck/tie/black,	10),
		new /datum/data/mining_equipment("scarf",	/obj/item/clothing/neck/vampire/scarf,	10),
		new /datum/data/mining_equipment("white scarf",	/obj/item/clothing/neck/vampire/scarf/white,	10),
		new /datum/data/mining_equipment("red scarf",	/obj/item/clothing/neck/vampire/scarf/red,	10),
		new /datum/data/mining_equipment("blue scarf",	/obj/item/clothing/neck/vampire/scarf/blue,	10),
		new /datum/data/mining_equipment("green scarf",	/obj/item/clothing/neck/vampire/scarf/green,	10),
		new /datum/data/mining_equipment("scarf",	/obj/item/clothing/neck/scarf, 10),
		new /datum/data/mining_equipment("black scarf",	/obj/item/clothing/neck/scarf/black,	10),
		new /datum/data/mining_equipment("red scarf",	/obj/item/clothing/neck/scarf/red,	10),
		new /datum/data/mining_equipment("blue scarf",	/obj/item/clothing/neck/scarf/darkblue,	10),
		new /datum/data/mining_equipment("large white scarf",	/obj/item/clothing/neck/large_scarf, 50),
		new /datum/data/mining_equipment("large red scarf",	/obj/item/clothing/neck/large_scarf/red,	10),
		new /datum/data/mining_equipment("large blue scarf",	/obj/item/clothing/neck/large_scarf/blue,	10),
		new /datum/data/mining_equipment("large green scarf",	/obj/item/clothing/neck/large_scarf/green, 10),
		new /datum/data/mining_equipment("large dark red scarf",	/obj/item/clothing/neck/large_scarf/syndie, 10),
		new /datum/data/mining_equipment("cane",	/obj/item/cane, 20),
		new /datum/data/mining_equipment("red lipstick",	/obj/item/lipstick, 10),
		new /datum/data/mining_equipment("black lipstick",	/obj/item/lipstick/black, 10),
		new /datum/data/mining_equipment("cross",	/obj/item/card/id/hunter,  25),
		new /datum/data/mining_equipment("dope chain", /obj/item/clothing/neck/necklace/dope, 7000),
		new /datum/data/mining_equipment("swag outfit", /obj/item/clothing/under/costume/swagoutfit, 2000),
		new /datum/data/mining_equipment("kasaya",	/obj/item/clothing/suit/vampire/kasaya,  15),
		new /datum/data/mining_equipment("imam's robe",	/obj/item/clothing/suit/vampire/imam,  15),
		new /datum/data/mining_equipment("orthodox robe",	/obj/item/clothing/suit/vampire/orthodox,  15),
		new /datum/data/mining_equipment("hijab",	/obj/item/clothing/head/vampire/hijab,  10),
		new /datum/data/mining_equipment("taqiyah",	/obj/item/clothing/head/vampire/taqiyah,  10),
		new /datum/data/mining_equipment("kalimavkion",	/obj/item/clothing/head/vampire/kalimavkion,  10),
		new /datum/data/mining_equipment("Nun Frock",	/obj/item/clothing/suit/vampire/nun,  15),
		new /datum/data/mining_equipment("Wimple",	/obj/item/clothing/head/vampire/nun,	10),
		new /datum/data/mining_equipment("duffelbag",	/obj/item/storage/backpack/duffelbag,	100),
		new /datum/data/mining_equipment("backpack",	/obj/item/storage/backpack,		100),
		new /datum/data/mining_equipment("satchel",		/obj/item/storage/backpack/satchel,		100),
		new /datum/data/mining_equipment("leather satchel",		/obj/item/storage/backpack/satchel/leather,		150),
		new /datum/data/mining_equipment("briefcase",		/obj/item/storage/briefcase,		100),
		// The Requiem Wardrobe Addition
		// REQUIEM WARDROBE ADDITION
		new /datum/data/mining_equipment("prescription aviators", /obj/item/clothing/glasses/vampire/vtr/metalframe, 20),
		new /datum/data/mining_equipment("green glasses", /obj/item/clothing/glasses/vampire/vtr/green, 20),
		new /datum/data/mining_equipment("hipster glasses", /obj/item/clothing/glasses/vampire/vtr/retro, 20),
		new /datum/data/mining_equipment("safety goggles", /obj/item/clothing/glasses/vampire/vtr/safetygoggles, 20),
		new /datum/data/mining_equipment("big sunglasses", /obj/item/clothing/glasses/vampire/vtr/bigsunglasses, 20),
		new /datum/data/mining_equipment("thin sunglasses", /obj/item/clothing/glasses/vampire/vtr/thinsunglasses, 20),
		new /datum/data/mining_equipment("aviators", /obj/item/clothing/glasses/vampire/vtr/aviator, 20),
		new /datum/data/mining_equipment("green aviators", /obj/item/clothing/glasses/vampire/vtr/aviator_green, 20),
		new /datum/data/mining_equipment("blue aviators", /obj/item/clothing/glasses/vampire/vtr/aviator_blue, 20),
		new /datum/data/mining_equipment("red aviators", /obj/item/clothing/glasses/vampire/vtr/aviator_red, 20),
		new /datum/data/mining_equipment("black flats", /obj/item/clothing/shoes/vampire/vtr/flats, 35),
		new /datum/data/mining_equipment("brown flats", /obj/item/clothing/shoes/vampire/vtr/flats/brown, 35),
		new /datum/data/mining_equipment("white flats", /obj/item/clothing/shoes/vampire/vtr/flats/white, 35),
		new /datum/data/mining_equipment("red flats", /obj/item/clothing/shoes/vampire/vtr/flats/red, 35),
		new /datum/data/mining_equipment("orange flats", /obj/item/clothing/shoes/vampire/vtr/flats/orange, 35),
		new /datum/data/mining_equipment("purple flats", /obj/item/clothing/shoes/vampire/vtr/flats/purple, 35),
		new /datum/data/mining_equipment("blue flats", /obj/item/clothing/shoes/vampire/vtr/flats/blue, 35),
		new /datum/data/mining_equipment("blue sneakers", /obj/item/clothing/shoes/vampire/vtr/sneakers_blue, 15),
		new /datum/data/mining_equipment("dark red cap", /obj/item/clothing/head/vampire/vtr/redsoft, 30),
		new /datum/data/mining_equipment("grey flatcap", /obj/item/clothing/head/vampire/vtr/gent_cap, 30),
		new /datum/data/mining_equipment("black flatcap", /obj/item/clothing/head/vampire/vtr/flatcap, 30),
		new /datum/data/mining_equipment("white flatcap", /obj/item/clothing/head/vampire/vtr/flatcap/white, 30),
		new /datum/data/mining_equipment("grey beret", /obj/item/clothing/head/vampire/vtr/beret_grey, 30),
		new /datum/data/mining_equipment("white beret", /obj/item/clothing/head/vampire/vtr/beret_white, 30),
		new /datum/data/mining_equipment("green utility cap", /obj/item/clothing/head/vampire/vtr/greenutil, 30),
		new /datum/data/mining_equipment("tan utility cap", /obj/item/clothing/head/vampire/vtr/tanutil, 30),
		new /datum/data/mining_equipment("boater hat", /obj/item/clothing/head/vampire/vtr/boater_hat, 30),
		new /datum/data/mining_equipment("wool hat", /obj/item/clothing/head/vampire/vtr/woolhat, 30),
		new /datum/data/mining_equipment("blue wool hat", /obj/item/clothing/head/vampire/vtr/woolhat_blue, 30),
		new /datum/data/mining_equipment("picture hat", /obj/item/clothing/head/vampire/vtr/picture_hat, 30),
		new /datum/data/mining_equipment("red picture hat", /obj/item/clothing/head/vampire/vtr/picture_red, 30),
		new /datum/data/mining_equipment("blue clipped tie", /obj/item/clothing/neck/vtr/tie/blueclip, 15),
		new /datum/data/mining_equipment("long blue tie", /obj/item/clothing/neck/vtr/tie/bluelong, 15),
		new /datum/data/mining_equipment("red clipped tie", /obj/item/clothing/neck/vtr/tie/redclip, 15),
		new /datum/data/mining_equipment("long red tie", /obj/item/clothing/neck/vtr/tie/redlong, 15),
		new /datum/data/mining_equipment("navy tie", /obj/item/clothing/neck/vtr/tie/navy, 15),
		new /datum/data/mining_equipment("yellow tie", /obj/item/clothing/neck/vtr/tie/yellow, 15),
		new /datum/data/mining_equipment("white tie", /obj/item/clothing/neck/vtr/tie/white, 15),
		new /datum/data/mining_equipment("green tie", /obj/item/clothing/neck/vtr/tie/darkgreen, 15),
		new /datum/data/mining_equipment("choker", /obj/item/clothing/neck/vtr/choker, 30),
		new /datum/data/mining_equipment("silver choker", /obj/item/clothing/neck/vtr/choker/silver, 30),
		new /datum/data/mining_equipment("ring choker", /obj/item/clothing/neck/vtr/choker/collar, 30),
		new /datum/data/mining_equipment("steel choker", /obj/item/clothing/neck/vtr/choker/collar/steel, 30),
		new /datum/data/mining_equipment("gold ring choker", /obj/item/clothing/neck/vtr/choker/collar/leatherg, 30),
		new /datum/data/mining_equipment("blue suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/blue, 45),
		new /datum/data/mining_equipment("purple suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/purple, 45),
		new /datum/data/mining_equipment("black suit jacket", /obj/item/clothing/suit/toggle/vtr/suitjacket/black, 45),
		new /datum/data/mining_equipment("black leather jacket", /obj/item/clothing/suit/toggle/vtr/leather, 45),
		new /datum/data/mining_equipment("brown leather jacket", /obj/item/clothing/suit/toggle/vtr/leather_brown, 45),
		new /datum/data/mining_equipment("black leather vest", /obj/item/clothing/suit/toggle/vtr/leather_sleeveless, 45),
		new /datum/data/mining_equipment("brown leather vest", /obj/item/clothing/suit/toggle/vtr/leather_brown_sleeveless, 45),
		new /datum/data/mining_equipment("grey zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_grey, 45),
		new /datum/data/mining_equipment("black zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_black, 45),
		new /datum/data/mining_equipment("red zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_red, 45),
		new /datum/data/mining_equipment("blue zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_blue, 45),
		new /datum/data/mining_equipment("orange zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_orange, 45),
		new /datum/data/mining_equipment("pink zipper hoodie", /obj/item/clothing/suit/toggle/vtr/hoodie_pink, 45),
		new /datum/data/mining_equipment("black track jacket", /obj/item/clothing/suit/toggle/vtr/trackjacket, 45),
		new /datum/data/mining_equipment("blue track jacket", /obj/item/clothing/suit/toggle/vtr/trackjacketblue, 45),
		new /datum/data/mining_equipment("green track jacket", /obj/item/clothing/suit/toggle/vtr/trackjacketgreen, 45),
		new /datum/data/mining_equipment("red track jacket", /obj/item/clothing/suit/toggle/vtr/trackjacketred, 45),
		new /datum/data/mining_equipment("white track jacket", /obj/item/clothing/suit/toggle/vtr/trackjacketwhite, 45),
		new /datum/data/mining_equipment("yellow fur-lined jacket", /obj/item/clothing/suit/toggle/vtr/yellow_dep_jacket, 45),
		new /datum/data/mining_equipment("red fur-lined jacket", /obj/item/clothing/suit/toggle/vtr/red_dep_jacket, 45),
		new /datum/data/mining_equipment("white fur-lined jacket", /obj/item/clothing/suit/toggle/vtr/white_dep_jacket, 45),
		new /datum/data/mining_equipment("brown fur-lined jacket", /obj/item/clothing/suit/toggle/vtr/brown_dep_jacket, 45),
		new /datum/data/mining_equipment("grey fur-linked jacket", /obj/item/clothing/suit/toggle/vtr/grey_dep_jacket, 45),
		new /datum/data/mining_equipment("blue fur-lined jacket", /obj/item/clothing/suit/toggle/vtr/blue_dep_jacket, 45),
		new /datum/data/mining_equipment("bomber jacket", /obj/item/clothing/suit/toggle/vtr/bomber, 45),
		new /datum/data/mining_equipment("asymmetrical bomber jacket", /obj/item/clothing/suit/toggle/vtr/retro_bomber, 45),
		new /datum/data/mining_equipment("grey flannel shirt", /obj/item/clothing/suit/vampire/vtr/flannel, 45),
		new /datum/data/mining_equipment("red flannel shirt", /obj/item/clothing/suit/vampire/vtr/flannel/red, 45),
		new /datum/data/mining_equipment("aqua flannel shirt", /obj/item/clothing/suit/vampire/vtr/flannel/aqua, 45),
		new /datum/data/mining_equipment("brown flannel shirt", /obj/item/clothing/suit/vampire/vtr/flannel/brown, 45),
		new /datum/data/mining_equipment("letterman jacket,  ULCA", /obj/item/clothing/suit/vampire/vtr/letterman_c, 45),
		new /datum/data/mining_equipment("black letterman jacket", /obj/item/clothing/suit/vampire/vtr/letterman_black, 45),
		new /datum/data/mining_equipment("purple letterman jacket", /obj/item/clothing/suit/vampire/vtr/letterman_purple, 45),
		new /datum/data/mining_equipment("white canvas jacket", /obj/item/clothing/suit/vampire/vtr/military_white, 45),
		new /datum/data/mining_equipment("tan canvas jacket", /obj/item/clothing/suit/vampire/vtr/military_tan, 45),
		new /datum/data/mining_equipment("navy canvas jacket", /obj/item/clothing/suit/vampire/vtr/military_navy, 45),
		new /datum/data/mining_equipment("gray canvas jacket", /obj/item/clothing/suit/vampire/vtr/military_grey, 45),
		new /datum/data/mining_equipment("black canvas jacket", /obj/item/clothing/suit/vampire/vtr/military_black, 45),
		new /datum/data/mining_equipment("yellow parka", /obj/item/clothing/suit/hooded/hoodie/parka_yellow, 45),
		new /datum/data/mining_equipment("red parka", /obj/item/clothing/suit/hooded/hoodie/parka_red, 45),
		new /datum/data/mining_equipment("purple parka", /obj/item/clothing/suit/hooded/hoodie/parka_purple, 45),
		new /datum/data/mining_equipment("green parka", /obj/item/clothing/suit/hooded/hoodie/parka_green, 45),
		new /datum/data/mining_equipment("blue parka", /obj/item/clothing/suit/hooded/hoodie/parka_blue, 45),
		new /datum/data/mining_equipment("vintage parka", /obj/item/clothing/suit/hooded/hoodie/parka_vintage, 45),
		new /datum/data/mining_equipment("high-waisted trousers", /obj/item/clothing/under/vampire/vtr/hightrousers, 50),
		new /datum/data/mining_equipment("high-waisted skirt", /obj/item/clothing/under/vampire/vtr/highskirt, 50),
		new /datum/data/mining_equipment("ripped punk jeans", /obj/item/clothing/under/vampire/vtr/rippedpunk, 50),
		new /datum/data/mining_equipment("grey suit slacks", /obj/item/clothing/under/vampire/vtr/suit, 35),
		new /datum/data/mining_equipment("white shirt and waistcoat", /obj/item/clothing/under/vampire/vtr/suit/waistcoat, 35),
		new /datum/data/mining_equipment("tan dress shirt", /obj/item/clothing/under/vampire/vtr/suit/tanshirt, 35),
		new /datum/data/mining_equipment("tan shirt and waistcoat", /obj/item/clothing/under/vampire/vtr/suit/tanshirtwaistcoat, 35),
		new /datum/data/mining_equipment("grey suit skirt", /obj/item/clothing/under/vampire/vtr/suit/greyskirt, 35),
		new /datum/data/mining_equipment("black suit slacks",/obj/item/clothing/under/vampire/vtr/suit/black, 35),
		new /datum/data/mining_equipment("black suit skirt", /obj/item/clothing/under/vampire/vtr/suit/blackskirt, 50),
		new /datum/data/mining_equipment("purple suit slacks", /obj/item/clothing/under/vampire/vtr/suit/purple, 35),
		new /datum/data/mining_equipment("charcoal suit slacks", /obj/item/clothing/under/vampire/vtr/suit/charcoal, 35),
		new /datum/data/mining_equipment("navy suit slacks", /obj/item/clothing/under/vampire/vtr/suit/navy, 35),
		new /datum/data/mining_equipment("burgundy suit slacks", /obj/item/clothing/under/vampire/vtr/suit/burgundy, 35),
		new /datum/data/mining_equipment("blue suit slacks", /obj/item/clothing/under/vampire/vtr/suit/blue, 35),
		new /datum/data/mining_equipment("checkered suit slacks", /obj/item/clothing/under/vampire/vtr/suit/checkered, 35),
		new /datum/data/mining_equipment("tan suit slacks", /obj/item/clothing/under/vampire/vtr/suit/tan, 35),
		new /datum/data/mining_equipment("purple suit skirt", /obj/item/clothing/under/vampire/vtr/suit/purpleskirt, 35),
		new /datum/data/mining_equipment("charcoal suit skirt", /obj/item/clothing/under/vampire/vtr/suit/charcoalskirt, 35),
		new /datum/data/mining_equipment("navy suit skirt", /obj/item/clothing/under/vampire/vtr/suit/navyskirt, 35),
		new /datum/data/mining_equipment("burgundy suit skirt", /obj/item/clothing/under/vampire/vtr/suit/burgundyskirt, 35),
		new /datum/data/mining_equipment("blue suit skirt", /obj/item/clothing/under/vampire/vtr/suit/blueskirt, 35),
		new /datum/data/mining_equipment("checkered suit skirt", /obj/item/clothing/under/vampire/vtr/suit/checkeredskirt, 35),
		new /datum/data/mining_equipment("tan suit skirt", /obj/item/clothing/under/vampire/vtr/suit/tanskirt, 35),
		new /datum/data/mining_equipment("black pantsuit", /obj/item/clothing/under/vampire/vtr/suit/blackfem, 100),
		new /datum/data/mining_equipment("corset and skirt outfit", /obj/item/clothing/under/vampire/vtr/dress/black_corset, 75),
		new /datum/data/mining_equipment("fancy red dress", /obj/item/clothing/under/vampire/vtr/dress/darkred, 75),
		new /datum/data/mining_equipment("red skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit, 35),
		new /datum/data/mining_equipment("blue plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_blue, 35),
		new /datum/data/mining_equipment("red plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_red, 35),
		new /datum/data/mining_equipment("purple plaid skirt", /obj/item/clothing/under/vampire/vtr/skirt/outfit/plaid_purple, 35),
		new /datum/data/mining_equipment("gothic dress", /obj/item/clothing/under/vampire/vtr/dress/gothic, 150),
		new /datum/data/mining_equipment("pentagram dress", /obj/item/clothing/under/vampire/vtr/dress/pentagram, 35),
		new /datum/data/mining_equipment("little black dress", /obj/item/clothing/under/vampire/vtr/dress/littleblackdress, 35),
		new /datum/data/mining_equipment("yellow swoop dress", /obj/item/clothing/under/vampire/vtr/dress/yellowswoop, 90),
		new /datum/data/mining_equipment("black tango dress", /obj/item/clothing/under/vampire/vtr/dress/blacktango, 35),
		new /datum/data/mining_equipment("slim qipao", /obj/item/clothing/under/vampire/vtr/dress/qipao2, 150),
		new /datum/data/mining_equipment("striped dress", /obj/item/clothing/under/vampire/vtr/dress/stripeddress, 35),
		new /datum/data/mining_equipment("sailor dress", /obj/item/clothing/under/vampire/vtr/dress/sailordress, 35),
		new /datum/data/mining_equipment("frilly black dress", /obj/item/clothing/under/vampire/vtr/dress/blackfrilly, 75),
		new /datum/data/mining_equipment("white lace dress", /obj/item/clothing/under/vampire/vtr/dress/wedding_gothic, 1505),
		new /datum/data/mining_equipment("witchy dress", /obj/item/clothing/under/vampire/vtr/dress/old_wench_dress, 100),
		new /datum/data/mining_equipment("countess dress", /obj/item/clothing/under/vampire/vtr/dress/countess, 7150),
		new /datum/data/mining_equipment("silk goddess dress", /obj/item/clothing/under/vampire/vtr/dress/goddess, 150),
		new /datum/data/mining_equipment("monochrome lace dress", /obj/item/clothing/under/vampire/vtr/dress/white_dress, 150),
		new /datum/data/mining_equipment("gold embroidered black dress", /obj/item/clothing/under/vampire/vtr/dress/sermon, 150),
		new /datum/data/mining_equipment("chain dress", /obj/item/clothing/under/vampire/vtr/dress/chain, 150),
		new /datum/data/mining_equipment("modest dress", /obj/item/clothing/under/vampire/vtr/dress/modest, 75),
		new /datum/data/mining_equipment("skater cargo pants", /obj/item/clothing/under/vampire/vtr/skater_boy, 75),
		new /datum/data/mining_equipment("skater skirt", /obj/item/clothing/under/vampire/vtr/skater_skirt, 75),
		new /datum/data/mining_equipment("strawberry lolita dress", /obj/item/clothing/under/vampire/vtr/dress/strawberrylolita, 150),
		new /datum/data/mining_equipment("widows dress", /obj/item/clothing/under/vampire/vtr/dress/matron, 150),
		new /datum/data/mining_equipment("little gothic dress", /obj/item/clothing/under/vampire/vtr/dress/maiden, 150),
		new /datum/data/mining_equipment("open front silk shirt", /obj/item/clothing/under/vampire/vtr/novella, 150),
		new /datum/data/mining_equipment("sheer black lace dress", /obj/item/clothing/under/vampire/vtr/dress/laceblack, 150),
		new /datum/data/mining_equipment("royal red suit", /obj/item/clothing/under/vampire/vtr/royalredsuit, 150),
		new /datum/data/mining_equipment("dark band t-shirt", /obj/item/clothing/under/vampire/vtr/bandshirt_dark, 35),
		new /datum/data/mining_equipment("light band t-shirt", /obj/item/clothing/under/vampire/vtr/bandshirt_light, 35),
		new /datum/data/mining_equipment("grey suspenders and trousers", /obj/item/clothing/under/vampire/vtr/suspenders, 35),
		new /datum/data/mining_equipment("black suspenders and trousers", /obj/item/clothing/under/vampire/vtr/suspenders_fancy, 35),
		new /datum/data/mining_equipment("red button-up", /obj/item/clothing/under/vampire/vtr/buttonup_red, 35),
		new /datum/data/mining_equipment("black baggy pants", /obj/item/clothing/under/vampire/vtr/pants/baggy, 35),
		new /datum/data/mining_equipment("black jeans", /obj/item/clothing/under/vampire/vtr/pants/blackjeans, 35),
		new /datum/data/mining_equipment("baggy black jeans", /obj/item/clothing/under/vampire/vtr/pants/blackjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped black jeans", /obj/item/clothing/under/vampire/vtr/pants/blackjeansripped, 35),
		new /datum/data/mining_equipment("grey jeans", /obj/item/clothing/under/vampire/vtr/pants/greyjeans, 35),
		new /datum/data/mining_equipment("baggy grey jeans", /obj/item/clothing/under/vampire/vtr/pants/greyjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped grey jeans", /obj/item/clothing/under/vampire/vtr/pants/greyjeansripped, 35),
		new /datum/data/mining_equipment("baggy classic jeans", /obj/item/clothing/under/vampire/vtr/pants/bluejeansbaggy, 35),
		new /datum/data/mining_equipment("ripped blue jeans", /obj/item/clothing/under/vampire/vtr/pants/bluejeansripped, 35),
		new /datum/data/mining_equipment("stonewashed jeans", /obj/item/clothing/under/vampire/vtr/pants/mustangjeans, 35),
		new /datum/data/mining_equipment("baggy stonewashed jeans", /obj/item/clothing/under/vampire/vtr/pants/mustangjeansbaggy, 35),
		new /datum/data/mining_equipment("ripped stonewashed jeans", /obj/item/clothing/under/vampire/vtr/pants/mustangjeansripped, 35),
		new /datum/data/mining_equipment("baggy camo pants", /obj/item/clothing/under/vampire/vtr/pants/camobaggy, 35),
		new /datum/data/mining_equipment("white pants", /obj/item/clothing/under/vampire/vtr/pants/white, 35),
		new /datum/data/mining_equipment("baggy white pants", /obj/item/clothing/under/vampire/vtr/pants/whitebaggy, 35),
		new /datum/data/mining_equipment("red pants", /obj/item/clothing/under/vampire/vtr/pants/red, 35),
		new /datum/data/mining_equipment("baggy red pants", /obj/item/clothing/under/vampire/vtr/pants/redbaggy, 35),
		new /datum/data/mining_equipment("khaki pants", /obj/item/clothing/under/vampire/vtr/pants/khaki, 35),
		new /datum/data/mining_equipment("baggy khaki pants", /obj/item/clothing/under/vampire/vtr/pants/khakibaggy, 35),
		new /datum/data/mining_equipment("blue trackpants", /obj/item/clothing/under/vampire/vtr/pants/trackpants/blue, 35),
		new /datum/data/mining_equipment("green trackpants", /obj/item/clothing/under/vampire/vtr/pants/trackpants/green, 35),
		new /datum/data/mining_equipment("red trackpants", /obj/item/clothing/under/vampire/vtr/pants/trackpants/red, 35),
		new /datum/data/mining_equipment("white trackpants", /obj/item/clothing/under/vampire/vtr/pants/trackpants/white, 35),
		new /datum/data/mining_equipment("black jeans shorts", /obj/item/clothing/under/vampire/vtr/shorts, 35),
		new /datum/data/mining_equipment("black jean shorts shorts", /obj/item/clothing/under/vampire/vtr/shorts/blackshortshort, 35),
		new /datum/data/mining_equipment("blue jean shorts", /obj/item/clothing/under/vampire/vtr/shorts/jeanshorts, 35),
		new /datum/data/mining_equipment("blue jean short shorts", /obj/item/clothing/under/vampire/vtr/shorts/jeanshortshort, 35),
		new /datum/data/mining_equipment("stonewashed jean shorts", /obj/item/clothing/under/vampire/vtr/shorts/mustangjeanshorts, 35),
		new /datum/data/mining_equipment("stonewashed jean short shorts", /obj/item/clothing/under/vampire/vtr/shorts/mustangjeanshortshort, 35),
		new /datum/data/mining_equipment("khaki shorts", /obj/item/clothing/under/vampire/vtr/shorts/khaki, 35),
		new /datum/data/mining_equipment("black leather skirt", /obj/item/clothing/under/vampire/vtr/shorts/skirt, 35),
		new /datum/data/mining_equipment("short denim skirt", /obj/item/clothing/under/vampire/vtr/shorts/skirtdenim, 35),
		new /datum/data/mining_equipment("white widows dress", /obj/item/clothing/under/vampire/vtr/dress/matron_white, 150),
		new /datum/data/mining_equipment("pinup skirt", /obj/item/clothing/under/vampire/vtr/pinup, 150),)
